apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-model
spec:
  selector:
    matchLabels:
      run: data-model
  replicas: 2
  template:
    metadata:
      labels:
        run: data-model
    spec:
      containers:
      - name: data-model
        image: rickywraith/stock-predict-dm:v2
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: data-model
  labels:
    run: data-model
spec:
  ports:
  - port: 8080

    protocol: TCP
  selector:
    run: data-model
