apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-service
spec:
  selector:
    matchLabels:
      run: s3-service
  replicas: 2
  template:
    metadata:
      labels:
        run: s3-service
    spec:
      containers:
      - name: s3-service
        image: rickywraith/stock-predict-s3:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub

---

apiVersion: v1
kind: Service
metadata:
  name: s3-service
  labels:
    run: s3-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: s3-service
