apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  selector:
    matchLabels:
      run: web-server
  replicas: 2
  template:
    metadata:
      labels:
        run: web-server
    spec:
      containers:
      - name: web-server
        image: rickywraith/stock-predict-dm:v2
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    run: web-server
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    run: web-server
