apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-dep
spec:
  selector:
    matchLabels:
      app: web-server-dep
  replicas: 2
  metadata:
    labels:
      app: web-server-dep
    spec:
      containers:
      - name: web-server
        image: rickywraith/stock-predict-ws:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: web-server
spec:
  type: LoadBalancer
  selector:
    app: web-server-dep
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000